// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: proto/connection.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_connection_proto protoreflect.FileDescriptor

var file_proto_connection_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x2f, 0x0a, 0x07, 0x41, 0x6d,
	0x6f, 0x6e, 0x67, 0x55, 0x73, 0x12, 0x24, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x07, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x07, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x6d, 0x76, 0x2f,
	0x61, 0x6d, 0x6f, 0x6e, 0x67, 0x2d, 0x75, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_connection_proto_rawDescOnce sync.Once
	file_proto_connection_proto_rawDescData = file_proto_connection_proto_rawDesc
)

func file_proto_connection_proto_rawDescGZIP() []byte {
	file_proto_connection_proto_rawDescOnce.Do(func() {
		file_proto_connection_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_connection_proto_rawDescData)
	})
	return file_proto_connection_proto_rawDescData
}

var file_proto_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_connection_proto_goTypes = []interface{}{
	(*Packet)(nil), // 0: Packet
}
var file_proto_connection_proto_depIdxs = []int32{
	0, // 0: AmongUs.Connection:input_type -> Packet
	0, // 1: AmongUs.Connection:output_type -> Packet
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_connection_proto_init() }
func file_proto_connection_proto_init() {
	if File_proto_connection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_connection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_connection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connection_proto_goTypes,
		DependencyIndexes: file_proto_connection_proto_depIdxs,
		MessageInfos:      file_proto_connection_proto_msgTypes,
	}.Build()
	File_proto_connection_proto = out.File
	file_proto_connection_proto_rawDesc = nil
	file_proto_connection_proto_goTypes = nil
	file_proto_connection_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AmongUsClient is the client API for AmongUs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AmongUsClient interface {
	Connection(ctx context.Context, opts ...grpc.CallOption) (AmongUs_ConnectionClient, error)
}

type amongUsClient struct {
	cc grpc.ClientConnInterface
}

func NewAmongUsClient(cc grpc.ClientConnInterface) AmongUsClient {
	return &amongUsClient{cc}
}

func (c *amongUsClient) Connection(ctx context.Context, opts ...grpc.CallOption) (AmongUs_ConnectionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AmongUs_serviceDesc.Streams[0], "/AmongUs/Connection", opts...)
	if err != nil {
		return nil, err
	}
	x := &amongUsConnectionClient{stream}
	return x, nil
}

type AmongUs_ConnectionClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type amongUsConnectionClient struct {
	grpc.ClientStream
}

func (x *amongUsConnectionClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *amongUsConnectionClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AmongUsServer is the server API for AmongUs service.
type AmongUsServer interface {
	Connection(AmongUs_ConnectionServer) error
}

// UnimplementedAmongUsServer can be embedded to have forward compatible implementations.
type UnimplementedAmongUsServer struct {
}

func (*UnimplementedAmongUsServer) Connection(AmongUs_ConnectionServer) error {
	return status.Errorf(codes.Unimplemented, "method Connection not implemented")
}

func RegisterAmongUsServer(s *grpc.Server, srv AmongUsServer) {
	s.RegisterService(&_AmongUs_serviceDesc, srv)
}

func _AmongUs_Connection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AmongUsServer).Connection(&amongUsConnectionServer{stream})
}

type AmongUs_ConnectionServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type amongUsConnectionServer struct {
	grpc.ServerStream
}

func (x *amongUsConnectionServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *amongUsConnectionServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AmongUs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AmongUs",
	HandlerType: (*AmongUsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connection",
			Handler:       _AmongUs_Connection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/connection.proto",
}
